package de.easygolfstats.types;

public enum CallbackResult {
    OK,
    MESSAGE_NOT_SEND,
    TIMEOUT,
    CONNECTION_EXCEPTION,
    INVALID_OPERATION,
    OPERATION_CANCELED,
    JSON_EXCEPTION,
    ERR_UNKNOWN,
    AN_ERROR,
    REST_EXCEPTION,
    EMPTY_USER,
    EMPTY_USER_ID,
    EMPTY_SESSION_ID,
    EMPTY_ENTITY_ID,
    EMPTY_HIT_CATEGORY,
    EMPTY_CLUB_TYPE,
    EMPTY_TOKDEN_ID,
    CREATE_DUPLICATE_KEY,
    ENTITY_NOT_FOUND,
    ENTITY_NOT_FOUND_BY_ID,
    INVALID_VALUE,
    MISSED_VALUE,
    UNKNOWN,
    ERR;
}
